version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: docs/source/conf.py
# Optionally set the version of Python and requirements required to build your docs
python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - myst_parser