name: Update docs/docs/index.md
on: push

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update docs/docs/index.md
        run: |
          echo "Generating docs/docs/index.md..."
          cat README.md > docs/docs/index.md
      - name: Commit and push changes
        run: |
          git config --global user.name ${{github.event.sender}}
          git config --global user.email ${{github.event.email}}
          git add docs/docs/index.md
          git commit -m "Update docs/docs/index.md"
          git push

    
