name: Update Index File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Index File
      run: |
        cp README.md docs/docs/index.md
        git add docs/docs/index.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update index.md file" --no-verify
        git push
