name: Update docs/docs/index.md
on: push

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update docs/docs/index.md
        run: |
          echo "Generating docs/docs/index.md..."
          cat README.md > docs/docs/index.md
      - name: Commit and push changes
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor_email }}
        run: |
          git add docs/docs/index.md
          git commit -m "Update docs/docs/index.md"
          git push

    
